### ISSUE TITLE
有木有与Czar.Cms相配的Login.cshtml界面

### ISSUE THREAD

**Issue by Inuyasha-Monster** [yilezhu/Czar.Cms#1]
力求风格保持一致即可 , 因为我看到源代码里面有login的影子 , 老哥有的话麻烦上传一下把 , 我这边正在基于此UI写后台权限中心 , 先行谢过了

**Comment by yilezhu** [comment]
dev分支登录样式已上传！这个样式我也在熟悉，前端是弱项，正在设计权限这块的样式呢
![image](https://user-images.githubusercontent.com/18655233/50899898-708ffd00-144e-11e9-9722-8a42b34331e1.png)
同时这个UI也是开源的，地址是：https://github.com/BrotherMa/layuiCMS2.0

**Comment by Inuyasha-Monster** [comment]
谢谢老铁 那我基于原始仓库组装我的后台吧 哈哈哈哈
