### ISSUE TITLE
麻烦提供数据库脚本

### ISSUE THREAD

**Issue by tiger2014** [yilezhu/Czar.Cms#2]
楼主提供的.bak文件只能再一定版本的sql上还原，所以麻烦提供一下带数据及数据结构的sql
![image](https://user-images.githubusercontent.com/6703612/54325417-06a5f680-463d-11e9-9d0f-06bb50c20d87.png)

**Comment by yilezhu** [comment]
这个最新的脚本我已经上传了，再pdm文件夹里面

**Comment by yilezhu** [comment]
没什么问题我关闭issue了！最新的脚本已经上传
