### ISSUE TITLE
感觉可优化

### ISSUE THREAD

**Issue by ghost** [yilezhu/Czar.Cms#3]
感谢作者大大的教程和文章，让我开始了第一个core的项目。代码自动生成里面 有一个dboption.cs CodeGenerateOption文件 有重复字段

**Comment by yilezhu** [comment]
具体是哪行代码，能具体点吗

**Comment by ghost** [comment]
大佬 很多通用方法可以二次封装吗 就是用户 文章 文章目录 获取列表 curd等  封装为泛型 不用又在每一个manager里面写？

**Comment by yilezhu** [comment]
这个已经封装了啊，baserepository基于sampleCRUD封装了基本的增删改查

**Comment by ghost** [comment]
我想试试直接在ui层里面调用一个方法 就ok 不用先在 server 接口里面添加并实现 然后在添加到 repository 里面 f但是那样又不符合 依赖于抽象的思想了 有什么好的建议吗

**Comment by yilezhu** [comment]
直接定义好接口，传接口好了
